version: '3.7'

services:
  teams_api:
    build:
        context: .
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on: 
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=teams_api_user
      - POSTGRES_PASSWORD=a256ccf990b0
      - POSTGRES_DB=teams_api_db

volumes:
  postgres_data:      